### ISSUE TITLE
Recent update (v3.11.2) git error

### ISSUE THREAD

**Issue by slimshizn** [nwithan8/tauticord#134]
```
fatal: not a git repository (or any of the parent directories): .git

Traceback (most recent call last):

  File "/app/run.py", line 51, in <module>

    logging.info(splash_logo())

  File "/app/modules/statics.py", line 75, in splash_logo

    last_commit = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode("utf-8").strip()

  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output

    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

  File "/usr/lib/python3.10/subprocess.py", line 526, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

2023-09-05T20:09:46: PM2 log: App [monitor:2] exited with code [1] via signal [SIGINT]

2023-09-05T20:09:46: PM2 log: App [monitor:2] starting in -fork mode-

2023-09-05T20:09:46: PM2 log: App [monitor:2] online

fatal: not a git repository (or any of the parent directories): .git

Traceback (most recent call last):

  File "/app/run.py", line 51, in <module>

    logging.info(splash_logo())

  File "/app/modules/statics.py", line 75, in splash_logo

    last_commit = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode("utf-8").strip()

  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output

    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

  File "/usr/lib/python3.10/subprocess.py", line 526, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

2023-09-05T20:09:47: PM2 log: App [monitor:2] exited with code [1] via signal [SIGINT]

2023-09-05T20:09:47: PM2 log: Script /app/run.py had too many unstable restarts (16). Stopped. "errored"
```

**Comment by nwithan8** [comment]
This was fixed in v3.11.2, can you please confirm that you're still having this issue on v3.11.2?

**Comment by slimshizn** [comment]
Yes, v3.11.2 as title states. Reverted to the version I was on previously (v3.10.6) so it's working for now. I can test again. Running in docker using the configuration file (config.yaml) still, is that still able to be used in the latest?

**Comment by nwithan8** [comment]
Should be, I'll try to have a release out later today to fix the bug so you won't have to revert for long.

**Comment by slimshizn** [comment]
I used git clone, then docker build.

**Comment by nwithan8** [comment]
Yep, that explains it.
