### ISSUE TITLE
Error on latest release v3.14.0

### ISSUE THREAD

**Issue by AntoineCardon** [nwithan8/tauticord#146]
Hello !

Since version v3.14.0

```
2024-01-28T01:37:34.262033454Z DEBUG:Count: 1
2024-01-28T01:37:34.359863902Z ERROR:Task exception was never retrieved
2024-01-28T01:37:34.360113092Z future: <Task finished name='Task-13' coro=<DiscordConnector.run_live_summary_service() done, defined at /app/modules/discord_connector.py:345> exception=SystemExit(1)>
2024-01-28T01:37:34.360262548Z Traceback (most recent call last):
2024-01-28T01:37:34.360371320Z   File "/app/modules/discord_connector.py", line 348, in run_live_summary_service
2024-01-28T01:37:34.360501587Z     message = await self.edit_summary_data(previous_message=message)
2024-01-28T01:37:34.360609587Z   File "/app/modules/discord_connector.py", line 395, in edit_summary_data
2024-01-28T01:37:34.360720803Z     await self.update_live_voice_channels(activity=activity,
2024-01-28T01:37:34.360824739Z TypeError: DiscordConnector.update_live_voice_channels() got an unexpected keyword argument 'use_status_emoji'
2024-01-28T01:37:34.360939702Z During handling of the above exception, another exception occurred:
2024-01-28T01:37:34.361044496Z Traceback (most recent call last):
2024-01-28T01:37:34.361151847Z   File "/app/run.py", line 83, in <module>
2024-01-28T01:37:34.361258114Z     discord_connector.connect()
2024-01-28T01:37:34.361363172Z   File "/app/modules/discord_connector.py", line 233, in connect
2024-01-28T01:37:34.361471198Z     self.client.run(self.token, reconnect=True)
2024-01-28T01:37:34.361586315Z   File "/usr/lib/python3.10/site-packages/discord/client.py", line 860, in run
2024-01-28T01:37:34.361691867Z     asyncio.run(runner())
2024-01-28T01:37:34.361796825Z   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2024-01-28T01:37:34.361895384Z     return loop.run_until_complete(main)
2024-01-28T01:37:34.362007419Z   File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
2024-01-28T01:37:34.362103529Z     self.run_forever()
2024-01-28T01:37:34.362205690Z   File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
2024-01-28T01:37:34.362302721Z     self._run_once()
2024-01-28T01:37:34.362402662Z   File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
2024-01-28T01:37:34.362514076Z     handle._run()
2024-01-28T01:37:34.362620192Z   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2024-01-28T01:37:34.362728191Z     self._context.run(self._callback, *self._args)
2024-01-28T01:37:34.362833430Z   File "/app/modules/discord_connector.py", line 351, in run_live_summary_service
2024-01-28T01:37:34.362929728Z     exit(1)  # Die on any unhandled exception for this subprocess (i.e. internet connection loss)
2024-01-28T01:37:34.363046712Z   File "/usr/lib/python3.10/_sitebuiltins.py", line 26, in __call__
2024-01-28T01:37:34.363150826Z     raise SystemExit(code)
2024-01-28T01:37:34.363253019Z SystemExit: 1
```

Even with 
      TC_VC_PLEX_STATUS_USE_EMOJI: "False"

going back to v3.13.0 work

Docker, Synology

**Comment by nwithan8** [comment]
Oops, got ahead of myself. Simple fix, patch incoming. Thanks for the heads up!
