### ISSUE TITLE
3.14.0 release break

### ISSUE THREAD

**Issue by Salpertio** [nwithan8/tauticord#147]
the previous release worked well (provided i make the bot admin, since it refused to operate with the require permissions listed in wiki/guide)  this release however breaks that previous fix

Version 3.14.0, Python 3.10.13 (main, Aug 26 2023, 11:33:35) [GCC 12.2.1 20220924]
Copyright © 2024 Nate Harris. All rights reserved.
2024-01-28 01:50:55,672 - [INFO]: Starting Tauticord...
DEBUG:Connected to Tautulli version: v2.13.4
2024-01-28 01:50:55,702 - [INFO]: Connecting to Discord...
INFO:Connecting to Discord...
2024-01-28 01:50:55 INFO     discord.client logging in using static token
INFO:logging in using static token
2024-01-28 01:50:56 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: x).
INFO:Shard ID None has connected to Gateway (Session ID: x).
2024-01-28 01:50:58,407 - [INFO]: Connected to Discord.
INFO:Connected to Discord.
2024-01-28 01:50:58,408 - [INFO]: Uploading required resources...
INFO:Uploading required resources...
2024-01-28 01:50:58,409 - [INFO]: Loading Tautulli voice settings...
INFO:Loading Tautulli voice settings...
2024-01-28 01:50:58,409 - [INFO]: Getting "Libraries" voice category
INFO:Getting "Libraries" voice category
2024-01-28 01:50:58,409 - [INFO]: "Libraries" voice category collected.
INFO:"Libraries" voice category collected.
2024-01-28 01:50:58,410 - [INFO]: Loading Tautulli summary service...
INFO:Loading Tautulli summary service...
2024-01-28 01:50:58,410 - [INFO]: Starting Tautulli library stats service...
INFO:Starting Tautulli library stats service...
DEBUG:JSON returned by GET request: {'stream_count': '0', 'sessions': [], 'stream_count_direct_play': 0, 'stream_count_direct_stream': 0, 'stream_count_transcode': 0, 'total_bandwidth': 0, 'lan_bandwidth': 0, 'wan_bandwidth': 0}
DEBUG:Count: 0
ERROR:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<DiscordConnector.run_live_summary_service() done, defined at /app/modules/discord_connector.py:345> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/app/modules/discord_connector.py", line 348, in run_live_summary_service
    message = await self.edit_summary_data(previous_message=message)
  File "/app/modules/discord_connector.py", line 395, in edit_summary_data
    await self.update_live_voice_channels(activity=activity,
TypeError: DiscordConnector.update_live_voice_channels() got an unexpected keyword argument 'use_status_emoji'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/run.py", line 83, in <module>
    discord_connector.connect()
  File "/app/modules/discord_connector.py", line 233, in connect
    self.client.run(self.token, reconnect=True)
  File "/usr/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/modules/discord_connector.py", line 351, in run_live_summary_service
    exit(1)  # Die on any unhandled exception for this subprocess (i.e. internet connection loss)
  File "/usr/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

unraid.

**Comment by nwithan8** [comment]
Thanks for the heads up. Quick fix, going out now.
