### ISSUE TITLE
Could not create text channel after latest update

### ISSUE THREAD

**Issue by milindpatel63** [nwithan8/tauticord#162]
```
2024-03-04 18:29:22,737 - [INFO]: Getting "c️urrently-playing" channel
INFO:Getting "c️urrently-playing" channel
2024-03-04 18:29:22,738 - [ERROR]: Could not load c️urrently-playing channel. Attempting to create...
ERROR:Could not load c️urrently-playing channel. Attempting to create...
2024-03-04 12:59:22 ERROR    discord.client Ignoring exception in on_ready
Traceback (most recent call last):
  File "/app/modules/discord_connector.py", line 109, in create_discord_channel
    return await guild.create_text_channel(name=channel_name, category=category)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_text_channel'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/app/modules/discord_connector.py", line 283, in on_ready
    await self.collect_discord_text_channel()
  File "/app/modules/discord_connector.py", line 482, in collect_discord_text_channel
    await get_discord_channel_by_name(client=self.client,
  File "/app/modules/discord_connector.py", line 147, in get_discord_channel_by_name
    return await create_discord_channel(client=client,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/modules/discord_connector.py", line 113, in create_discord_channel
    raise Exception(f"Could not create channel {channel_name}")
Exception: Could not create channel c️urrently-playing
ERROR:Ignoring exception in on_ready
Traceback (most recent call last):
  File "/app/modules/discord_connector.py", line 109, in create_discord_channel
    return await guild.create_text_channel(name=channel_name, category=category)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_text_channel'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/app/modules/discord_connector.py", line 283, in on_ready
    await self.collect_discord_text_channel()
  File "/app/modules/discord_connector.py", line 482, in collect_discord_text_channel
    await get_discord_channel_by_name(client=self.client,
  File "/app/modules/discord_connector.py", line 147, in get_discord_channel_by_name
    return await create_discord_channel(client=client,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/modules/discord_connector.py", line 113, in create_discord_channel
    raise Exception(f"Could not create channel {channel_name}")
Exception: Could not create channel c️urrently-playing
```

**Comment by milindpatel63** [comment]
Have tried everything in the name,
With space
Without space
all lowercase
double quotes in docker compose file
single quote in docker compose file

Even tried giving administrator permission to the bot in discord, so it's not a permission issue.

**Comment by milindpatel63** [comment]
I tried switching back to previous 3.18.0 version, but still the same issue. Could be something from discord;s side? Maybe some changes in their api?

**Comment by nwithan8** [comment]
```
Traceback (most recent call last):
  File "/app/modules/discord_connector.py", line 109, in create_discord_channel
    return await guild.create_text_channel(name=channel_name, category=category)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_text_channel'
```

https://github.com/nwithan8/tauticord/blob/master/modules/discord_connector.py#L104

The `guild` variable is empty because it couldn't load the guild from the guild ID provided.

Check the `ServerID` in your config file: https://github.com/nwithan8/tauticord/blob/99484c3ad4f2e0327d35bf6918775272dce2ba22/config.yaml.example#L74C5-L74C13

**Comment by Turge08** [comment]
I have the same problem. This was working before. While troubleshooting, I delete all of the channels and categories and still having this issue, even when rolling back to 3.18 as OP mentioned.

<pre>2024-03-04 11:35:03,529 - [INFO]: Getting "tauticord" channel
INFO:Getting "tauticord" channel
2024-03-04 11:35:03,529 - [ERROR]: Could not load tauticord channel. Attempting to create...
ERROR:Could not load tauticord channel. Attempting to create...
2024-03-04 16:35:03 ERROR    discord.client Ignoring exception in on_ready
Traceback (most recent call last):
  File "/app/modules/discord_connector.py", line 109, in create_discord_channel
    return await guild.create_text_channel(name=channel_name, category=category)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_text_channel'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/app/modules/discord_connector.py", line 283, in on_ready
    await self.collect_discord_text_channel()
  File "/app/modules/discord_connector.py", line 482, in collect_discord_text_channel
    await get_discord_channel_by_name(client=self.client,
  File "/app/modules/discord_connector.py", line 147, in get_discord_channel_by_name
    return await create_discord_channel(client=client,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/modules/discord_connector.py", line 113, in create_discord_channel
    raise Exception(f"Could not create channel {channel_name}")
Exception: Could not create channel tauticord
ERROR:Ignoring exception in on_ready
Traceback (most recent call last):
  File "/app/modules/discord_connector.py", line 109, in create_discord_channel
    return await guild.create_text_channel(name=channel_name, category=category)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_text_channel'</pre>

**Comment by Turge08** [comment]
Ok, so it looks like my server ID changed. I updated it and the channels populated immediately.

**Comment by Turge08** [comment]
Ok so I just realized it wasn't the server ID that was in there before but the Application ID. Not sure how it worked before with the app id but updating it with the server id definitely fixed it.

**Comment by milindpatel63** [comment]
> > Ok, so it looks like my server ID changed. I updated it and the channels populated immediately.
> 
> Odd that your server ID would have changed, but glad you got it working again.
> 
> Future versions of Tauticord will have a better error message to clarify this issue.
> 
> @milindpatel63 Can you confirm if this is the same issue you ran into?

Yes it seems my server got changed too.
If it keeps changing for no reason within such short time (i just copied it a day back and it changed now), then this is not a reliable way to configure.
Is there any way you could obtain server id by authenticating once with discord?

**Comment by milindpatel63** [comment]
ok so i think the server id getting changed was the issue of my docker management service which i'm using called "Dockge". It was showing my previous compose file with different server id for some reason. Weird.

Also, @nwithan8  i have another issue.
The Text channel name that we specify via "TC_DISCORD_CHANNEL_NAME" env variable, it keeps recreating the same channel again and again after restart.
I noticed, there was a previous issue regarding this, and i made sure to write the name in all lowercase, even without space, and it still is creating a new channel every restart. The only fix for this right now is to not use the env variable which defaults the name to "tauticord" and then it doesn't create a new one for some reason.

**Comment by nwithan8** [comment]
> ok so i think the server id getting changed was the issue of my docker management service which i'm using called "Dockge". It was showing my previous compose file with different server id for some reason. Weird.
> 
> Also, @nwithan8 i have another issue. The Text channel name that we specify via "TC_DISCORD_CHANNEL_NAME" env variable, it keeps recreating the same channel again and again after restart. I noticed, there was a previous issue regarding this, and i made sure to write the name in all lowercase, even without space, and it still is creating a new channel every restart. The only fix for this right now is to not use the env variable which defaults the name to "tauticord" and then it doesn't create a new one for some reason.

Can you share your logs? You can DM me in Discord.

**Comment by milindpatel63** [comment]
> > ok so i think the server id getting changed was the issue of my docker management service which i'm using called "Dockge". It was showing my previous compose file with different server id for some reason. Weird.
> > Also, @nwithan8 i have another issue. The Text channel name that we specify via "TC_DISCORD_CHANNEL_NAME" env variable, it keeps recreating the same channel again and again after restart. I noticed, there was a previous issue regarding this, and i made sure to write the name in all lowercase, even without space, and it still is creating a new channel every restart. The only fix for this right now is to not use the env variable which defaults the name to "tauticord" and then it doesn't create a new one for some reason.
> 
> Can you share your logs? You can DM me in Discord.

Sure, here's my docker logs after restarting where it created the same channel again

```
2024-03-05T02:28:29: PM2 log: Launching in no daemon mode
2024-03-05T02:28:29: PM2 log: App [keepalive:0] starting in -fork mode-
2024-03-05T02:28:29: PM2 log: [Watch] Start watching tauticord
2024-03-05T02:28:29: PM2 log: App [tauticord:1] starting in -fork mode-
2024-03-05T02:28:29: PM2 log: App [keepalive:0] online
2024-03-05T02:28:29: PM2 log: App [tauticord:1] online
2024-03-05 02:28:31,377 - [INFO]: 
___________________  ______________________________________________ 
___  __/__    |_  / / /__  __/___  _/_  ____/_  __ \__  __ \__  __ \
__  /  __  /| |  / / /__  /   __  / _  /    _  / / /_  /_/ /_  / / /
_  /   _  ___ / /_/ / _  /   __/ /  / /___  / /_/ /_  _, _/_  /_/ / 
/_/    /_/  |_\____/  /_/    /___/  \____/  \____/ /_/ |_| /_____/  
Version 3.19.0, Python 3.11.8 (main, Feb 19 2024, 17:01:17) [GCC 13.2.1 20231014]
Copyright © 2024 Nate Harris. All rights reserved.
2024-03-05 02:28:31,380 - [INFO]: Starting Tauticord...
DEBUG:Connected to Tautulli version: v2.13.4
2024-03-05 02:28:31,423 - [INFO]: Connecting to Discord...
INFO:Connecting to Discord...
2024-03-04 20:58:31 INFO     discord.client logging in using static token
INFO:logging in using static token
2024-03-04 20:58:34 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 0a91987c7846e08cc4b3f3419dcd04d5).
INFO:Shard ID None has connected to Gateway (Session ID: 0a91987c7846e08cc4b3f3419dcd04d5).
2024-03-05 02:28:36,315 - [INFO]: Connected to Discord.
INFO:Connected to Discord.
2024-03-05 02:28:36,316 - [INFO]: Uploading required resources...
INFO:Uploading required resources...
2024-03-05 02:28:36,317 - [INFO]: Loading Tautulli text settings...
INFO:Loading Tautulli text settings...
2024-03-05 02:28:36,317 - [INFO]: Getting "️currentlyplaying" channel
INFO:Getting "️currentlyplaying" channel
2024-03-05 02:28:36,318 - [ERROR]: Could not load ️currentlyplaying channel. Attempting to create...
ERROR:Could not load ️currentlyplaying channel. Attempting to create...
2024-03-05 02:28:36,809 - [INFO]: "️currentlyplaying" channel collected.
INFO:"️currentlyplaying" channel collected.
2024-03-05 02:28:37,282 - [INFO]: Couldn't find old message, sending initial message...
INFO:Couldn't find old message, sending initial message...
2024-03-05 02:28:37,733 - [INFO]: Loading Tautulli voice settings...
INFO:Loading Tautulli voice settings...
2024-03-05 02:28:37,735 - [INFO]: Getting "Plex Stream Stats" voice category
INFO:Getting "Plex Stream Stats" voice category
2024-03-05 02:28:37,743 - [INFO]: "Plex Stream Stats" voice category collected.
INFO:"Plex Stream Stats" voice category collected.
2024-03-05 02:28:37,751 - [INFO]: Getting "Plex Library Stats" voice category
INFO:Getting "Plex Library Stats" voice category
2024-03-05 02:28:37,751 - [INFO]: "Plex Library Stats" voice category collected.
INFO:"Plex Library Stats" voice category collected.
2024-03-05 02:28:37,752 - [INFO]: Getting "Server Performance" voice category
INFO:Getting "Server Performance" voice category
2024-03-05 02:28:37,752 - [INFO]: "Server Performance" voice category collected.
INFO:"Server Performance" voice category collected.
2024-03-05 02:28:37,752 - [INFO]: Loading Tautulli summary service...
INFO:Loading Tautulli summary service...
2024-03-05 02:28:37,752 - [INFO]: Starting Tautulli library stats service...
INFO:Starting Tautulli library stats service...
2024-03-05 02:28:37,752 - [INFO]: Starting performance monitoring service...
INFO:Starting performance monitoring service...
DEBUG:JSON returned by GET request: {'stream_count': '0', 'sessions': [], 'stream_count_direct_play': 0, 'stream_count_direct_stream': 0, 'stream_count_transcode': 0, 'total_bandwidth': 0, 'lan_bandwidth': 0, 'wan_bandwidth': 0}
DEBUG:Count: 0
2024-03-05 02:28:37,821 - [INFO]: Updating Plex Status voice channel with new status: Online
INFO:Updating Plex Status voice channel with new status: Online
2024-03-05 02:28:37,825 - [INFO]: Updating library stats...
INFO:Updating library stats...
2024-03-05 02:28:37,831 - [INFO]: Collecting stats about library "Movies"
INFO:Collecting stats about library "Movies"
DEBUG:JSON returned by GET request: {'row_id': 6, 'server_id': 'f51858661fffc3b1a03b9f128a020efcb52e0ded', 'section_id': 1, 'section_name': 'Movies', 'section_type': 'movie', 'library_thumb': '/:/resources/movie.png', 'library_art': '/:/resources/movie-fanart.jpg', 'count': 397, 'parent_count': None, 'child_count': None, 'is_active': 1, 'do_notify': 1, 'do_notify_created': 1, 'keep_history': 1, 'deleted_section': 0, 'last_accessed': None}
2024-03-05 02:28:37,893 - [INFO]: Collecting stats about library "TV Shows"
INFO:Collecting stats about library "TV Shows"
DEBUG:JSON returned by GET request: {'row_id': 7, 'server_id': 'f51858661fffc3b1a03b9f128a020efcb52e0ded', 'section_id': 4, 'section_name': 'TV Shows', 'section_type': 'show', 'library_thumb': '/:/resources/show.png', 'library_art': '/:/resources/show-fanart.jpg', 'count': 6, 'parent_count': 10, 'child_count': 149, 'is_active': 1, 'do_notify': 1, 'do_notify_created': 1, 'keep_history': 1, 'deleted_section': 0, 'last_accessed': None}
2024-03-05 02:28:37,929 - [INFO]: Collecting stats about library "Music"
INFO:Collecting stats about library "Music"
DEBUG:JSON returned by GET request: {'row_id': 12, 'server_id': 'f51858661fffc3b1a03b9f128a020efcb52e0ded', 'section_id': 7, 'section_name': 'Music', 'section_type': 'artist', 'library_thumb': '/:/resources/artist.png', 'library_art': '/:/resources/artist-fanart.jpg', 'count': 52, 'parent_count': 86, 'child_count': 111, 'is_active': 1, 'do_notify': 1, 'do_notify_created': 1, 'keep_history': 1, 'deleted_section': 0, 'last_accessed': None}
2024-03-05 02:28:37,959 - [INFO]: Collecting stats about library "Movies 4K DolbyVision"
INFO:Collecting stats about library "Movies 4K DolbyVision"
2024-03-05 02:28:37,994 - [INFO]: Collecting stats about library "TV Shows 4K DolbyVision"
INFO:Collecting stats about library "TV Shows 4K DolbyVision"
2024-03-05 02:28:38,107 - [INFO]: Updating Movies voice channel with new library size: 397
INFO:Updating Movies voice channel with new library size: 397
2024-03-05 02:28:38,110 - [INFO]: Updating performance stats...
INFO:Updating performance stats...
2024-03-05 02:28:38,153 - [INFO]: Updating Users voice channel with new user count: 15
INFO:Updating Users voice channel with new user count: 15
2024-03-05 02:28:38,649 - [INFO]: Updating Streams voice channel with new stream count: 0
INFO:Updating Streams voice channel with new stream count: 0
2024-03-05 02:28:38,663 - [INFO]: Updating Disk voice channel with new disk space: 4.1 TB/5 TB (83.21%)
INFO:Updating Disk voice channel with new disk space: 4.1 TB/5 TB (83.21%)
2024-03-05 02:28:38,685 - [INFO]: Updating TV Shows voice channel with new library size: 6
INFO:Updating TV Shows voice channel with new library size: 6
2024-03-05 02:28:39,123 - [INFO]: Updating Transcodes voice channel with new stream count: 0
INFO:Updating Transcodes voice channel with new stream count: 0
2024-03-05 02:28:40,240 - [INFO]: Updating CPU voice channel with new CPU percent: 26.5%
INFO:Updating CPU voice channel with new CPU percent: 26.5%
2024-03-05 02:28:40,247 - [INFO]: Updating Music voice channel with new library size: 111
INFO:Updating Music voice channel with new library size: 111
2024-03-05 02:28:40,250 - [INFO]: Updating Bandwidth voice channel with new bandwidth: 0.0 bps
INFO:Updating Bandwidth voice channel with new bandwidth: 0.0 bps
2024-03-05 02:28:40,678 - [INFO]: Updating Local Bandwidth voice channel with new bandwidth: 0.0 bps
INFO:Updating Local Bandwidth voice channel with new bandwidth: 0.0 bps
2024-03-05 02:28:40,738 - [INFO]: Updating Movies 4K DV voice channel with new library size: 0
INFO:Updating Movies 4K DV voice channel with new library size: 0
2024-03-04 20:58:40 WARNING  discord.http We are being rate limited. PATCH https://discord.com/api/v10/channels/1213889093868716062 responded with 429. Retrying in 498.65 seconds.
WARNING:We are being rate limited. PATCH https://discord.com/api/v10/channels/1213889093868716062 responded with 429. Retrying in 498.65 seconds.
2024-03-05 02:28:41,201 - [INFO]: Updating Remote Bandwidth voice channel with new bandwidth: 0.0 bps
INFO:Updating Remote Bandwidth voice channel with new bandwidth: 0.0 bps
2024-03-05 02:28:41,240 - [INFO]: Updating TV Shows 4K DV voice channel with new library size: 1
INFO:Updating TV Shows 4K DV voice channel with new library size: 1
DEBUG:Using old message...
DEBUG:Editing old message...
```

![image](https://github.com/nwithan8/tauticord/assets/11052427/4645e542-ca8a-4da3-b122-3b471dbe32d5)

**Comment by nwithan8** [comment]
@milindpatel63 Would you mind sharing your configuration with me privately?

**Comment by milindpatel63** [comment]
Okay so, i decided to investigate this further, since looking at your code, i'm shocked too as to why this was happening.

In short, it was a weird typing error with some invisible character. I don't know how this happened.

Look at this docker compose file
```
version: "3.9"
services:
  tauticord:
    image: nwithan8/tauticord:latest
    container_name: tauticord
    volumes:
      - /home/user/Docker/tauticord/config:/config
      - /home/user/Docker/tauticord/logs:/logs
      - /media/hdd/Videos:/monitor
    network_mode: host
    restart: no
    environment:
      TC_DISCORD_BOT_TOKEN: redacted
      TC_TAUTULLI_KEY: redacted
      TC_TAUTULLI_URL: http://localhost:8181
      TC_USE_SELF_SIGNED_CERT: "False"
      TC_REFRESH_SECONDS: 30
      TC_TERMINATE_MESSAGE: Your stream has been killed. Kindly contact server owner.
      TC_SERVER_NAME: PlexServer
      TC_USE_24_HOUR_TIME: "True"
      TC_HIDE_USERNAMES: "False"
      TC_HIDE_PLATFORMS: "False"
      TC_HIDE_PLAYER_NAMES: "False"
      TC_HIDE_QUALITY: "False"
      TC_HIDE_BANDWIDTH: "False"
      TC_HIDE_TRANSCODE: "False"
      TC_HIDE_PROGRESS: "False"
      TC_HIDE_ETA: "False"
      TC_USE_FRIENDLY_NAMES: "True"
      TC_THOUSANDS_SEPARATOR: ""
      TC_VC_STATS_CATEGORY_NAME: Plex Stream Stats
      TC_VC_STREAM_COUNT: "True"
      TC_VC_STREAM_COUNT_CHANNEL_ID: 0
      TC_VC_TRANSCODE_COUNT: "True"
      TC_VC_TRANSCODE_COUNT_CHANNEL_ID: 0
      TC_VC_BANDWIDTH: "True"
      TC_VC_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_LOCAL_BANDWIDTH: "True"
      TC_VC_LOCAL_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_REMOTE_BANDWIDTH: "True"
      TC_VC_REMOTE_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_PLEX_STATUS: "True"
      TC_VC_PLEX_STATUS_USE_EMOJI: "False"
      TC_VC_PLEX_STATUS_CHANNEL_ID: 0
      TC_VC_LIBRARIES_CATEGORY_NAME: Plex Library Stats
      TC_VC_LIBRARY_STATS: "True"
      TC_VC_LIBRARY_NAMES: Movies,TV Shows,Music
      TC_VC_COMBINED_LIBRARIES: Movies 4K DV%Movies 4K DolbyVision,TV Shows 4K DV%TV Shows 4K DolbyVision
      TC_VC_LIBRARY_REFRESH_SECONDS: 3600
      TC_VC_LIBRARY_USE_EMOJIS: "True"
      TC_VC_TV_SERIES_COUNT: "True"
      TC_VC_TV_EPISODE_COUNT: "False"
      TC_VC_MUSIC_ARTIST_COUNT: "False"
      TC_VC_MUSIC_TRACK_COUNT: "True"
      TC_DISCORD_ADMIN_IDS: redacted
      TC_DISCORD_POST_SUMMARY_MESSAGE: "True"
      TC_DISCORD_CHANNEL_NAME: ️currentlyplaying
      #TC_DISCORD_CHANNEL_NAME: currentlyplaying
      TC_DISCORD_NITRO: "False"
      TC_ALLOW_ANALYTICS: "False"
      TC_VC_PERFORMANCE_CATEGORY_NAME: Server Performance
      TC_MONITOR_CPU: "True"
      TC_MONITOR_MEMORY: "True"
      TC_MONITOR_TAUTULLI_USER_COUNT: "True"
      TC_MONITOR_DISK_SPACE: "True"
      TZ: Asia/Calcutta
networks: {}
```
Look at `TC_DISCORD_CHANNEL_NAME` env variable. There are two of them, one of them is commented out.
The original one causing all the issue is the top one, and the bottom one which is commented out is what i typed again.

The bottom one is not causing that issue, but the top one is. Both of them look identical.
But i compared both of them in vscode, and behold

![image](https://github.com/nwithan8/tauticord/assets/11052427/eb01c55c-a948-4171-8332-ad2a6de2e60f)

The top one has some weird character in it. I can delete it using backspace.

Really sorry to disturb you with this issue which was clearly my fault.
Great program btw. 👍️

My issue is resolved now. Thanks.

**Comment by nwithan8** [comment]
Wow, that's wild. Glad you got it figured out!
