### ISSUE TITLE
Shard ID None blocked for more than x seconds

### ISSUE THREAD

**Issue by TheMonDon** [nwithan8/tauticord#23]
I'm unsure where to begin with this, bot appears online but doesn't seem to be able to create any channels or anything, the bot has every permission.

Full error:

```john@WebServer:~/discord/tauticord$ python3 Tauticord.py
WARNING:PyNaCl is not installed, voice will NOT be supported
WARNING:Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/john/discord/tauticord/Tauticord.py", line 40, in <module>
    d.connect()
  File "/home/john/discord/tauticord/modules/discord_connector.py", line 107, in connect
    self.client.run(self.token)
  File "/home/john/.local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/john/.local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/john/discord/tauticord/modules/discord_connector.py", line 103, in on_ready
    await start_bot(discord_connector=self, analytics=self.analytics)
  File "/home/john/discord/tauticord/modules/discord_connector.py", line 19, in start_bot
    analytics.event(event_category="Platform", event_action=sys.platform)
  File "/home/john/discord/tauticord/modules/analytics.py", line 68, in event
    return self._send(final_params=final_params)
  File "/home/john/discord/tauticord/modules/analytics.py", line 46, in _send
    if objectrest.post(url=url):
  File "/home/john/.local/lib/python3.9/site-packages/objectrest/base_requests.py", line 142, in post
    return _make_request(request_type=RequestType.POST, url=url, session=session, use_proxy=use_proxy, log=log,
  File "/home/john/.local/lib/python3.9/site-packages/objectrest/base_requests.py", line 39, in _make_request
    res = session.post(url, **kwargs) if session else requests.post(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)```

Edit;
After letting it go through the whole thing after a minute and a half it does seem to work, although if has more errors.

```ERROR:Could not load Status channel. Attempting to create...
<Message id=938164175883096084 channel=<TextChannel id=938164174838726696 name='status' position=13 nsfw=False news=False category_id=None> type=<MessageType.default: 0> author=<Member id=938156002711335024 name='Tautulli' discriminator='3489' bot=True nick=None guild=<Guild id=937128957604691999 name='The Plex Center' shard_id=None chunked=False member_count=5>> flags=<MessageFlags value=0>>
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/john/discord/tauticord/modules/discord_connector.py", line 102, in on_ready
    self.update_libraries.start()
  File "/home/john/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 205, in start
    raise RuntimeError('Task is already launched and is not completed.')
RuntimeError: Task is already launched and is not completed.```

**Comment by nwithan8** [comment]
Thanks for the logs, will look into it.

**Comment by nwithan8** [comment]
Bug was most likely fixed during recent renovation. Closing for now.
