### ISSUE TITLE
Missing Permissions?

### ISSUE THREAD

**Issue by slimshizn** [nwithan8/tauticord#27]
after running docker run, this is my output.

WARNING:PyNaCl is not installed, voice will NOT be supported
Ignoring exception in on_ready

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 343, in _run_event

    await coro(*args, **kwargs)

  File "/app/modules/discord_connector.py", line 130, in on_ready

    await start_bot(discord_connector=self, analytics=self.analytics)

  File "/app/modules/discord_connector.py", line 22, in start_bot

    message = await discord_connector.get_old_message_in_tautulli_channel()

  File "/app/modules/discord_connector.py", line 321, in get_old_message_in_tautulli_channel

    await send_starter_message(tautulli_connector=self.tautulli, discord_channel=self.tautulli_channel)

  File "/app/modules/discord_connector.py", line 74, in send_starter_message

    await discord_channel.send(embed=embed)

  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1065, in send

    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,

  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 248, in request

    raise Forbidden(r, data)

discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

**Comment by nwithan8** [comment]
Make sure the bot has permissions to post in the Discord channel.

**Comment by slimshizn** [comment]
Ah, that was it. Working. Thank you.
