### ISSUE TITLE
Unable to launch docker

### ISSUE THREAD

**Issue by themaluxis** [nwithan8/tauticord#35]
I try to use it on Unraid docker (its on prupose in apps community)
but i get this error ;(

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/confuse/yaml_util.py", line 86, in load_yaml
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./Tauticord.py", line 12, in <module>
    config = config_parser.Config(app_name="Tauticord", config_path="config.yaml")
  File "/app/modules/config_parser.py", line 206, in __init__
    self.config.set_file(filename=config_path)
  File "/usr/local/lib/python3.10/site-packages/confuse/core.py", line 604, in set_file
    self.set(YamlSource(filename, base_for_paths=base_for_paths,
  File "/usr/local/lib/python3.10/site-packages/confuse/sources.py", line 76, in __init__
    self.load()
  File "/usr/local/lib/python3.10/site-packages/confuse/sources.py", line 84, in load
    value = yaml_util.load_yaml(self.filename,
  File "/usr/local/lib/python3.10/site-packages/confuse/yaml_util.py", line 89, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.exceptions.ConfigReadError: /app/config.yaml could not be read: [Errno 2] No such file or directory: '/app/config.yaml'`

**Comment by nwithan8** [comment]
Thanks for letting me know, patch incoming.

**Comment by nwithan8** [comment]
@themaluxis Docker image has been updated.
