### ISSUE TITLE
Traceback errors

### ISSUE THREAD

**Issue by slimshizn** [nwithan8/tauticord#38]
```
[2022-09-12 20:42:29] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/app/modules/discord_connector.py", line 130, in on_ready
    await start_bot(discord_connector=self, analytics=self.analytics)
  File "/app/modules/discord_connector.py", line 24, in start_bot
    message = await discord_connector.edit_message(previous_message=message)
  File "/app/modules/discord_connector.py", line 173, in edit_message
    new_message = await send_message(content=data_wrapper,
  File "/app/modules/discord_connector.py", line 96, in send_message
    await message.edit(content=content.message)
  File "/usr/local/lib/python3.10/site-packages/discord/message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
ERROR:Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/app/modules/discord_connector.py", line 130, in on_ready
    await start_bot(discord_connector=self, analytics=self.analytics)
  File "/app/modules/discord_connector.py", line 24, in start_bot
    message = await discord_connector.edit_message(previous_message=message)
  File "/app/modules/discord_connector.py", line 173, in edit_message
    new_message = await send_message(content=data_wrapper,
  File "/app/modules/discord_connector.py", line 96, in send_message
    await message.edit(content=content.message)
  File "/usr/local/lib/python3.10/site-packages/discord/message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
```

**Comment by nwithan8** [comment]
This has been fixed in the latest release (1.0.4)
