### ISSUE TITLE
syntax error after update

### ISSUE THREAD

**Issue by Glitch3dPenguin** [nwithan8/tauticord#42]
After the update. I tried to run the program after getting the new requirements but it seems there may be an issue. 

```
root@plex:/etc/tauticord# python3 Tauticord.py
Traceback (most recent call last):
  File "/etc/tauticord/Tauticord.py", line 7, in <module>
    import modules.discord_connector as discord
  File "/etc/tauticord/modules/discord_connector.py", line 122
    match channel_type:
          ^
SyntaxError: invalid syntax
```

**Comment by Glitch3dPenguin** [comment]
Python needs to now be 3.10 or later. 
Issue fixed.

**Comment by nwithan8** [comment]
Thanks for reminding me to call that out.
