### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by slimshizn** [nwithan8/tauticord#46]
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event

    await coro(*args, **kwargs)

  File "/app/modules/discord_connector.py", line 240, in on_raw_reaction_add

    message = await self.tautulli_channel.fetch_message(payload.message_id)

  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1599, in fetch_message

    data = await self._state.http.get_message(channel.id, id)

  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 740, in request

    raise NotFound(response, data)

discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

ERROR:Ignoring exception in on_raw_reaction_add

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event

    await coro(*args, **kwargs)

  File "/app/modules/discord_connector.py", line 240, in on_raw_reaction_add

    message = await self.tautulli_channel.fetch_message(payload.message_id)

  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1599, in fetch_message

    data = await self._state.http.get_message(channel.id, id)

  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 740, in request

    raise NotFound(response, data)

discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

[2022-10-26 01:09:57] [ERROR   ] discord.client: Ignoring exception in on_raw_reaction_add

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event

    await coro(*args, **kwargs)

  File "/app/modules/discord_connector.py", line 240, in on_raw_reaction_add

    message = await self.tautulli_channel.fetch_message(payload.message_id)

  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1599, in fetch_message

    data = await self._state.http.get_message(channel.id, id)

  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 740, in request

    raise NotFound(response, data)

discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

ERROR:Ignoring exception in on_raw_reaction_add

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event

    await coro(*args, **kwargs)

  File "/app/modules/discord_connector.py", line 240, in on_raw_reaction_add

    message = await self.tautulli_channel.fetch_message(payload.message_id)

  File "/usr/local/lib/python3.10/site-packages/discord/abc.py", line 1599, in fetch_message

    data = await self._state.http.get_message(channel.id, id)

  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 740, in request

    raise NotFound(response, data)

discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

**Comment by nwithan8** [comment]
Try deleting the last message in whatever channel Tauticord posts in.

**Comment by slimshizn** [comment]
Done, I'll let it sit overnight see what happens. Thanks for the quick reply.

**Comment by slimshizn** [comment]
```
 message = await self.edit_summary_message(previous_message=message)

  File "/app/modules/discord_connector.py", line 288, in edit_summary_message

    data_wrapper, count, activity = self.tautulli.refresh_data()

  File "/app/modules/tautulli_connector.py", line 307, in refresh_data

    data = self.api.activity()

  File "/usr/local/lib/python3.10/site-packages/tautulli/internal/decorators.py", line 80, in wrapper

    json_data = self._get_json(command=command, params=params)

  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 86, in _get_json

    response = self._get(command=command, params=params)

  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 73, in _get

    return self._session.get(url=self._url, params=params)

  File "/usr/local/lib/python3.10/site-packages/objectrest/session.py", line 12, in get

    return self._session.get(url, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get

    return self.request("GET", url, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send

    resp = conn.urlopen(

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen

    httplib_response = self._make_request(

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request

    httplib_response = conn.getresponse()

  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse

    response.begin()

  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin

    version, status, reason = self._read_status()

  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto

    return self._sock.recv_into(b)

  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into

    return self.read(nbytes, buffer)

  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read

    return self._sslobj.read(len, buffer)

WARNING:Shard ID None heartbeat blocked for more than 10 seconds.

Loop thread traceback (most recent call last):

  File "/app/./Tauticord.py", line 42, in <module>

    d.connect()

  File "/app/modules/discord_connector.py", line 206, in connect

    self.client.run(self.token)

  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 828, in run

    asyncio.run(runner())

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete

    self.run_forever()

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

    self._run_once()

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1899, in _run_once

    handle._run()

  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run

    self._context.run(self._callback, *self._args)

  File "/app/modules/discord_connector.py", line 259, in run_live_summary_message_service

    message = await self.edit_summary_message(previous_message=message)

  File "/app/modules/discord_connector.py", line 288, in edit_summary_message

    data_wrapper, count, activity = self.tautulli.refresh_data()

  File "/app/modules/tautulli_connector.py", line 307, in refresh_data

    data = self.api.activity()

  File "/usr/local/lib/python3.10/site-packages/tautulli/internal/decorators.py", line 80, in wrapper

    json_data = self._get_json(command=command, params=params)

  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 86, in _get_json

    response = self._get(command=command, params=params)

  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 73, in _get

    return self._session.get(url=self._url, params=params)

  File "/usr/local/lib/python3.10/site-packages/objectrest/session.py", line 12, in get

    return self._session.get(url, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get

    return self.request("GET", url, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send

    resp = conn.urlopen(

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen

    httplib_response = self._make_request(

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request

    httplib_response = conn.getresponse()

  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse

    response.begin()

  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin

    version, status, reason = self._read_status()

  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto

    return self._sock.recv_into(b)

  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into

    return self.read(nbytes, buffer)

  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read

    return self._sslobj.read(len, buffer)
    ```

**Comment by nwithan8** [comment]
Looks like the API call to Tautulli failed due to an SSL error. Are you using HTTP or HTTPS to connect to Tautulli?

**Comment by slimshizn** [comment]
HTTPS, I did a reboot of both services and so far it's running fine, and has updated the library stats finally. I'll continue to watch but close for now. Thanks.
