### ISSUE TITLE
Exception: Tautulli did not report a version number.

### ISSUE THREAD

**Issue by dsmitty166** [nwithan8/tauticord#48]
Hello - I'm seeing this on a fresh deployment on unraid, any ideas?

Traceback (most recent call last):
  File "/app/./Tauticord.py", line 31, in <module>
    tautulli_connector=tautulli.TautulliConnector(
  File "/app/modules/tautulli_connector.py", line 290, in __init__
    self.api = tautulli.RawAPI(base_url=base_url, api_key=api_key)
  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 29, in __init__
    if verify and not self._verify_compatibility(min_version=__min_api_version__):
  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 47, in _verify_compatibility
    raise Exception("Tautulli did not report a version number.")
Exception: Tautulli did not report a version number.
Traceback (most recent call last):
  File "/app/./Tauticord.py", line 31, in <module>
    tautulli_connector=tautulli.TautulliConnector(
  File "/app/modules/tautulli_connector.py", line 290, in __init__
    self.api = tautulli.RawAPI(base_url=base_url, api_key=api_key)
  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 29, in __init__
    if verify and not self._verify_compatibility(min_version=__min_api_version__):
  File "/usr/local/lib/python3.10/site-packages/tautulli/api/json_api.py", line 47, in _verify_compatibility
    raise Exception("Tautulli did not report a version number.")
Exception: Tautulli did not report a version number.

**Comment by nwithan8** [comment]
Tauticord has to verify that it is compatible with the version of Tautulli it's trying to communicate with.

Looks like your Tautulli server didn't provide a version number as expected.

Is your Tautulli server on? What version of Tautulli are you using?

**Comment by dsmitty166** [comment]
It is running, yep. Although I just realized I have a base url set to /tautulli. Could that be the issue?

VERSION V2.10.5

**Comment by dsmitty166** [comment]
Actually, it looks like that is the case, permissions error now, so making progress

**Comment by dsmitty166** [comment]
Bingo - I just had to add /tautulli to the end of my URL - working well now, thanks!
