### ISSUE TITLE
Error on Latest Version

### ISSUE THREAD

**Issue by JamsRepos** [nwithan8/tauticord#93]
Using the latest docker image. 

```
2023-06-04T18:25:07: PM2 log: App [monitor:2] online
Traceback (most recent call last):
  File "/app/run.py", line 7, in <module>
    import modules.discord_connector as discord
  File "/app/modules/discord_connector.py", line 10, in <module>
    import modules.system_stats as system_stats
  File "/app/modules/system_stats.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
2023-06-04T18:25:08: PM2 log: App [monitor:2] exited with code [1] via signal [SIGINT]
2023-06-04T18:25:08: PM2 log: App [monitor:2] starting in -fork mode-
2023-06-04T18:25:08: PM2 log: App [monitor:2] online```

**Comment by nwithan8** [comment]
Oops, forgot a dependency. Mental note failed me, fix incoming
